//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarSalesView
    {
        public string BarOrQ { get; set; }
        public Nullable<System.DateTime> DateTimeCollected { get; set; }
        public string DrinkName { get; set; }
        public Nullable<decimal> DrinkSize { get; set; }
        public string DrinkNameAndSize { get; set; }
        public Nullable<int> QTYOrdered { get; set; }
        public string CategoryNameOfMenuItemAtTimeOfBuying { get; set; }
        public Nullable<decimal> PriceAtTimeOfBuying { get; set; }
        public int OrderCollected { get; set; }
        public int DeliveredByHotel { get; set; }
        public Nullable<decimal> FinalAmountOfOrder { get; set; }
        public int HotelID { get; set; }
        public Nullable<int> StaffMemberWhoStartedOrderName { get; set; }
        public Nullable<int> StaffMemberWhoStartedOrderID { get; set; }
        public Nullable<int> StaffMemberWhoCompletedOrderName { get; set; }
        public Nullable<int> StaffMemberWhoCompletedOrderID { get; set; }
        public string StaffMemberWhoDeliveredOrderName { get; set; }
        public int StaffMemberWhoDeliveredOrderID { get; set; }
    }
}
