//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrinkingBuddyEntities : DbContext
    {
        public DrinkingBuddyEntities()
            : base("name=DrinkingBuddyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DrinkStandardImage> DrinkStandardImages { get; set; }
        public virtual DbSet<FAKE_MonthlySales> FAKE_MonthlySales { get; set; }
        public virtual DbSet<FAKE_MonthlySales2> FAKE_MonthlySales2 { get; set; }
        public virtual DbSet<HotelBarSale> HotelBarSales { get; set; }
        public virtual DbSet<HotelBarSalesDetail> HotelBarSalesDetails { get; set; }
        public virtual DbSet<HotelDiscountReason> HotelDiscountReasons { get; set; }
        public virtual DbSet<HotelDiscountsGiven> HotelDiscountsGivens { get; set; }
        public virtual DbSet<HotelEmployee> HotelEmployees { get; set; }
        public virtual DbSet<HotelEmployeesAvailabilityTime> HotelEmployeesAvailabilityTimes { get; set; }
        public virtual DbSet<HotelEmployeesRoster> HotelEmployeesRosters { get; set; }
        public virtual DbSet<HotelInventory> HotelInventories { get; set; }
        public virtual DbSet<HotelMarketingCoupon> HotelMarketingCoupons { get; set; }
        public virtual DbSet<HotelMarketingCouponsPatron> HotelMarketingCouponsPatrons { get; set; }
        public virtual DbSet<HotelMarketingNewsletter> HotelMarketingNewsletters { get; set; }
        public virtual DbSet<HotelMarketingNewslettersPatron> HotelMarketingNewslettersPatrons { get; set; }
        public virtual DbSet<HotelMarketingPushNotification> HotelMarketingPushNotifications { get; set; }
        public virtual DbSet<HotelMarketingPushNotificationsPatron> HotelMarketingPushNotificationsPatrons { get; set; }
        public virtual DbSet<HotelMarketingSm> HotelMarketingSms { get; set; }
        public virtual DbSet<HotelMarketingSmsPatron> HotelMarketingSmsPatrons { get; set; }
        public virtual DbSet<HotelMenu> HotelMenus { get; set; }
        public virtual DbSet<HotelMenusCategory> HotelMenusCategories { get; set; }
        public virtual DbSet<HotelMenusExtraDetail> HotelMenusExtraDetails { get; set; }
        public virtual DbSet<HotelMenusInventoryUse> HotelMenusInventoryUses { get; set; }
        public virtual DbSet<HotelMenusSubCategory> HotelMenusSubCategories { get; set; }
        public virtual DbSet<HotelOpenHour> HotelOpenHours { get; set; }
        public virtual DbSet<HotelRefundReason> HotelRefundReasons { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelSavedOrder> HotelSavedOrders { get; set; }
        public virtual DbSet<HotelSavedOrdersDetail> HotelSavedOrdersDetails { get; set; }
        public virtual DbSet<HotelSpecial> HotelSpecials { get; set; }
        public virtual DbSet<HotelSpecialsMeta> HotelSpecialsMetas { get; set; }
        public virtual DbSet<HotelTaxGroup> HotelTaxGroups { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
        public virtual DbSet<PatronsGroup> PatronsGroups { get; set; }
        public virtual DbSet<PatronsGroupsMember> PatronsGroupsMembers { get; set; }
        public virtual DbSet<PatronsHotelLogIn> PatronsHotelLogIns { get; set; }
        public virtual DbSet<PatronsHotelSubscription> PatronsHotelSubscriptions { get; set; }
        public virtual DbSet<PatronsOrder> PatronsOrders { get; set; }
        public virtual DbSet<PatronsOrdersDetail> PatronsOrdersDetails { get; set; }
        public virtual DbSet<PatronsOrdersFastestWay> PatronsOrdersFastestWays { get; set; }
        public virtual DbSet<PatronsOrdersRefund> PatronsOrdersRefunds { get; set; }
        public virtual DbSet<PatronsOrdersRefundsDetail> PatronsOrdersRefundsDetails { get; set; }
        public virtual DbSet<PatronsPaymentMethod> PatronsPaymentMethods { get; set; }
        public virtual DbSet<PatronsPreference> PatronsPreferences { get; set; }
        public virtual DbSet<PatronsSessionToken> PatronsSessionTokens { get; set; }
        public virtual DbSet<StatesG> StatesGs { get; set; }
        public virtual DbSet<PatronsResetPasswordToken> PatronsResetPasswordTokens { get; set; }
    }
}
