//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAKE_MonthlySales2
    {
        public int FAKE_MonthlySales2ID { get; set; }
        public Nullable<decimal> JanSales { get; set; }
        public Nullable<decimal> JanProfit { get; set; }
        public Nullable<decimal> FebSales { get; set; }
        public Nullable<decimal> FebProfit { get; set; }
        public Nullable<decimal> MarSales { get; set; }
        public Nullable<decimal> MarProfit { get; set; }
        public Nullable<decimal> AprilSales { get; set; }
        public Nullable<decimal> AprilProfit { get; set; }
        public Nullable<decimal> MaySales { get; set; }
        public Nullable<decimal> MayProfit { get; set; }
        public Nullable<decimal> JuneSales { get; set; }
        public Nullable<decimal> JuneProfit { get; set; }
        public Nullable<int> CatID { get; set; }
    }
}
