//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAKE_MonthlySales
    {
        public int FAKE_MonthlySalesID { get; set; }
        public string MonthG { get; set; }
        public Nullable<decimal> MonthlySales { get; set; }
        public Nullable<decimal> MonthlyProfit { get; set; }
        public Nullable<int> MonthlyCatID { get; set; }
        public Nullable<int> MonthOrder { get; set; }
    }
}
