//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDiscountReason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelDiscountReason()
        {
            this.HotelDiscountsGivens = new HashSet<HotelDiscountsGiven>();
        }
    
        public int HotelDiscountReasonID { get; set; }
        public int HotelID { get; set; }
        public string DiscountReason { get; set; }
        public string AmountOrPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public bool AllowUserOverride { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelDiscountsGiven> HotelDiscountsGivens { get; set; }
    }
}
