//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelTaxGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelTaxGroup()
        {
            this.HotelMenus = new HashSet<HotelMenu>();
        }
    
        public int HotelTaxGroupID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public string TaxGroupName { get; set; }
        public Nullable<int> TaxGroupPercentage { get; set; }
        public bool PriceIsTaxInclusive { get; set; }
        public bool IsActive { get; set; }
        public int StateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMenu> HotelMenus { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
