//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelMarketingPushNotificationsPatron
    {
        public int HotelMarketingPushNotificationsPatronID { get; set; }
        public int HotelMarketingPushNotificationsID { get; set; }
        public int PatronID { get; set; }
    
        public virtual HotelMarketingPushNotification HotelMarketingPushNotification { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
