//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelMenusSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelMenusSubCategory()
        {
            this.HotelMenus = new HashSet<HotelMenu>();
            this.HotelSpecials = new HashSet<HotelSpecial>();
        }
    
        public int HotelMenusSubCategoryID { get; set; }
        public int HotelID { get; set; }
        public int HotelMenuCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public bool IsActive { get; set; }
        public byte[] SubCategoryImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMenu> HotelMenus { get; set; }
        public virtual HotelMenusCategory HotelMenusCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelSpecial> HotelSpecials { get; set; }
    }
}
