//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.HotelBarSales = new HashSet<HotelBarSale>();
            this.HotelDiscountReasons = new HashSet<HotelDiscountReason>();
            this.HotelDiscountsGivens = new HashSet<HotelDiscountsGiven>();
            this.HotelEmployees = new HashSet<HotelEmployee>();
            this.HotelEmployeesAvailabilityTimes = new HashSet<HotelEmployeesAvailabilityTime>();
            this.HotelInventories = new HashSet<HotelInventory>();
            this.HotelMarketingNewsletters = new HashSet<HotelMarketingNewsletter>();
            this.HotelMarketingPushNotifications = new HashSet<HotelMarketingPushNotification>();
            this.HotelMarketingSms = new HashSet<HotelMarketingSm>();
            this.HotelMenus = new HashSet<HotelMenu>();
            this.HotelOpenHours = new HashSet<HotelOpenHour>();
            this.HotelRefundReasons = new HashSet<HotelRefundReason>();
            this.HotelSavedOrders = new HashSet<HotelSavedOrder>();
            this.HotelTaxGroups = new HashSet<HotelTaxGroup>();
            this.PatronsHotelLogIns = new HashSet<PatronsHotelLogIn>();
            this.PatronsHotelSubscriptions = new HashSet<PatronsHotelSubscription>();
            this.PatronsOrders = new HashSet<PatronsOrder>();
            this.PatronsOrdersRefunds = new HashSet<PatronsOrdersRefund>();
            this.TrackGroupOrders = new HashSet<TrackGroupOrder>();
        }
    
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string HotelAddress1 { get; set; }
        public string HotelAddress2 { get; set; }
        public string HotelSuburb { get; set; }
        public string HotelPostcode { get; set; }
        public Nullable<int> HotelStateID { get; set; }
        public byte[] HotelLogo { get; set; }
        public bool UseStartOrder { get; set; }
        public bool UseSpecialCodeForPickup { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterAccount { get; set; }
        public Nullable<decimal> HotelLat { get; set; }
        public Nullable<decimal> HotelLong { get; set; }
        public string OptionBarSalesFirstOrderOrFastestWay { get; set; }
        public bool UseLocationsForOrders { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelBarSale> HotelBarSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelDiscountReason> HotelDiscountReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelDiscountsGiven> HotelDiscountsGivens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelEmployee> HotelEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelEmployeesAvailabilityTime> HotelEmployeesAvailabilityTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelInventory> HotelInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMarketingNewsletter> HotelMarketingNewsletters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMarketingPushNotification> HotelMarketingPushNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMarketingSm> HotelMarketingSms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMenu> HotelMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelOpenHour> HotelOpenHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRefundReason> HotelRefundReasons { get; set; }
        public virtual StatesG StatesG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelSavedOrder> HotelSavedOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelTaxGroup> HotelTaxGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronsHotelLogIn> PatronsHotelLogIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronsHotelSubscription> PatronsHotelSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronsOrder> PatronsOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronsOrdersRefund> PatronsOrdersRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackGroupOrder> TrackGroupOrders { get; set; }
    }
}
