//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelEmployeesRoster
    {
        public int HotelEmployeesRosterID { get; set; }
        public int HotelEmployeeID { get; set; }
        public Nullable<System.DateTime> DateOfShift { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool OngoingWeekly { get; set; }
        public Nullable<int> PaidBreakMins { get; set; }
        public Nullable<int> UnPaidBreakMins { get; set; }
    
        public virtual HotelEmployee HotelEmployee { get; set; }
    }
}
