//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelSavedOrdersDetail
    {
        public int HotelSavedOrderDetailsID { get; set; }
        public int HotelSavedOrderID { get; set; }
        public Nullable<int> HotelMenuID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> PriceAtTimeOfSave { get; set; }
        public string OtherDescription { get; set; }
    
        public virtual HotelSavedOrder HotelSavedOrder { get; set; }
    }
}
