//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelMenu()
        {
            this.HotelBarSalesDetails = new HashSet<HotelBarSalesDetail>();
            this.HotelMenusExtraDetails = new HashSet<HotelMenusExtraDetail>();
            this.HotelMenusInventoryUses = new HashSet<HotelMenusInventoryUse>();
            this.HotelSpecials = new HashSet<HotelSpecial>();
            this.PatronsOrdersDetails = new HashSet<PatronsOrdersDetail>();
        }
    
        public int HotelMenuID { get; set; }
        public int HotelID { get; set; }
        public int HotelCategoryID { get; set; }
        public Nullable<int> HotelSubCategoryID { get; set; }
        public string DrinkName { get; set; }
        public Nullable<decimal> DrinkSize { get; set; }
        public string DrinkUnitMlLitreUnit { get; set; }
        public Nullable<decimal> DrinkPrice { get; set; }
        public byte[] DrinkImage { get; set; }
        public Nullable<int> MinutesToServeItem { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> CostOfItem { get; set; }
        public bool OnBarSalesQuickList { get; set; }
        public Nullable<int> HotelTaxGroupID { get; set; }
        public string IngredientsForPatronsApp { get; set; }
        public string WhereFromForPatronsApp { get; set; }
        public string PercentAlcoholForPatronsApp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelBarSalesDetail> HotelBarSalesDetails { get; set; }
        public virtual HotelMenusCategory HotelMenusCategory { get; set; }
        public virtual HotelMenusSubCategory HotelMenusSubCategory { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual HotelTaxGroup HotelTaxGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMenusExtraDetail> HotelMenusExtraDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMenusInventoryUse> HotelMenusInventoryUses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelSpecial> HotelSpecials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronsOrdersDetail> PatronsOrdersDetails { get; set; }
    }
}
