//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelOpenHour
    {
        public int HotelOpenHoursID { get; set; }
        public int HotelID { get; set; }
        public Nullable<System.DateTime> MondayOpen { get; set; }
        public Nullable<System.DateTime> MondayClose { get; set; }
        public Nullable<System.DateTime> TuesdayOpen { get; set; }
        public Nullable<System.DateTime> TuesdayClose { get; set; }
        public Nullable<System.DateTime> WednesdayOpen { get; set; }
        public Nullable<System.DateTime> WednesdayClose { get; set; }
        public Nullable<System.DateTime> ThursdayOpen { get; set; }
        public Nullable<System.DateTime> ThursdayClose { get; set; }
        public Nullable<System.DateTime> FridayOpen { get; set; }
        public Nullable<System.DateTime> FridayClose { get; set; }
        public Nullable<System.DateTime> SaturdayOpen { get; set; }
        public Nullable<System.DateTime> SaturdayClose { get; set; }
        public Nullable<System.DateTime> SundayOpen { get; set; }
        public Nullable<System.DateTime> SundayClose { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
