//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelSavedOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelSavedOrder()
        {
            this.HotelSavedOrdersDetails = new HashSet<HotelSavedOrdersDetail>();
        }
    
        public int HotelSavedOrderID { get; set; }
        public int HotelID { get; set; }
        public int HotelEmployeeID { get; set; }
        public Nullable<System.DateTime> DateOrderSaved { get; set; }
    
        public virtual HotelEmployee HotelEmployee { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelSavedOrdersDetail> HotelSavedOrdersDetails { get; set; }
    }
}
