//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBarSalesDetail
    {
        public int HotelBarSalesDetailsID { get; set; }
        public int HotelBarSalesID { get; set; }
        public int HotelMenuItemID { get; set; }
        public Nullable<int> QTYOrdered { get; set; }
        public Nullable<int> HotelSpecialID { get; set; }
        public Nullable<decimal> AcceptedPricePerItem { get; set; }
        public string CategoryNameOfMenuItemAtTimeOfBuying { get; set; }
        public string SubCategoryNameOfMenuIteAtTimeOfBuying { get; set; }
        public string ItemNameAtTimeOfBuying { get; set; }
        public Nullable<int> HotelSpecialsIDAtTimeOfBuying { get; set; }
        public Nullable<decimal> PriceAtTimeOfBuying { get; set; }
        public string SizeAtTimeOfBuying { get; set; }
        public string CategoryNameOfSpecialAtTimeOfBuying { get; set; }
        public string SubCategoryNameOfSpecialAtTimeOfBuying { get; set; }
        public string DiscountTypeAtTimeOfBuying { get; set; }
        public Nullable<int> DiscountPercentAtTimeOfBuying { get; set; }
        public Nullable<decimal> NewAmountAtTimeOfBuying { get; set; }
        public string DescriptionOfSpecialAtTimeOfBuying { get; set; }
        public Nullable<System.DateTime> StartDateAtTimeOfBuying { get; set; }
        public Nullable<System.DateTime> EndDateAtTimeOfBuying { get; set; }
        public Nullable<System.TimeSpan> StartTimeAtTimeOfBuying { get; set; }
        public Nullable<System.TimeSpan> EndTimeAtTimeOfBuying { get; set; }
        public string RepeatIntervalAtTimeOfBuying { get; set; }
        public Nullable<int> RepeatEveryXWeeksAtTimeOfBuying { get; set; }
        public bool RepeatEveryXWeeksMondayAtTimeOfBuying { get; set; }
        public bool RepeatEveryXWeeksTuesdayAtTimeOfBuying { get; set; }
        public bool RepeatEveryXWeeksWednesdayAtTimeOfBuying { get; set; }
        public bool RepeatEveryXWeeksThursdayAtTimeOfBuying { get; set; }
        public bool RepeatEveryXWeeksFridayAtTimeOfBuying { get; set; }
        public bool RepeatEveryXWeeksSaturdayAtTimeOfBuying { get; set; }
        public bool RepeatEveryXWeeksSundayAtTimeOfBuying { get; set; }
        public Nullable<int> RepeatMonthlyDayAtTimeOfBuying { get; set; }
        public Nullable<System.DateTime> RepeatYearlyDateAtTimeOfBuying { get; set; }
        public Nullable<bool> RepeatDailyEveryDayAtTimeOfBuying { get; set; }
    
        public virtual HotelBarSale HotelBarSale { get; set; }
        public virtual HotelMenu HotelMenu { get; set; }
    }
}
