//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelInventory()
        {
            this.HotelMenusInventoryUses = new HashSet<HotelMenusInventoryUse>();
        }
    
        public int HotelInventoryID { get; set; }
        public int HotelID { get; set; }
        public string InventoryItemName { get; set; }
        public decimal InventoryItemSize { get; set; }
        public string MlLitreOrUnit { get; set; }
        public Nullable<decimal> InventoryItemPrice { get; set; }
        public Nullable<decimal> CurrentQty { get; set; }
        public System.DateTime DateTimeLastUpdate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelMenusInventoryUse> HotelMenusInventoryUses { get; set; }
    }
}
