//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelEmployeesAvailabilityTime
    {
        public int HotelEmployeesAvailabilityTimeID { get; set; }
        public int HotelID { get; set; }
        public int EmployeeID { get; set; }
        public string DayOfWeek { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> ActiveStartDate { get; set; }
        public Nullable<System.DateTime> ActiveEndDate { get; set; }
        public string Comment { get; set; }
    
        public virtual HotelEmployee HotelEmployee { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
