//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelSpecial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelSpecial()
        {
            this.HotelSpecialsMetas = new HashSet<HotelSpecialsMeta>();
            this.PatronsOrdersDetails = new HashSet<PatronsOrdersDetail>();
        }
    
        public int HotelSpecialID { get; set; }
        public int HotelID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> HotelMenuID { get; set; }
        public bool WillRepeat { get; set; }
        public string DiscountType { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmountNOTINUSE { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public string DescriptionOfSpecial { get; set; }
    
        public virtual HotelMenu HotelMenu { get; set; }
        public virtual HotelMenusCategory HotelMenusCategory { get; set; }
        public virtual HotelMenusSubCategory HotelMenusSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelSpecialsMeta> HotelSpecialsMetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronsOrdersDetail> PatronsOrdersDetails { get; set; }
    }
}
