//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelMenusInventoryUse
    {
        public int HotelMenusInventoryUseID { get; set; }
        public int HotelMenuID { get; set; }
        public int HotelInventoryID { get; set; }
        public decimal UseQty { get; set; }
        public string MlLtrOrUnit { get; set; }
    
        public virtual HotelInventory HotelInventory { get; set; }
        public virtual HotelMenu HotelMenu { get; set; }
    }
}
