//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsGroupsMember
    {
        public int PatronsGroupsMembersID { get; set; }
        public int PatronsGroupID { get; set; }
        public int MemberPatronID { get; set; }
        public Nullable<System.DateTime> DateTimeJoinedGroup { get; set; }
        public Nullable<System.DateTime> DateTimeLeftGroup { get; set; }
    }
}
