//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronCreditTransection
    {
        public int PatronCreditTransectionID { get; set; }
        public Nullable<int> PatronID { get; set; }
        public Nullable<decimal> Credit_Amount { get; set; }
        public Nullable<System.DateTime> CreditDatetime { get; set; }
        public Nullable<decimal> Previouse_Balance { get; set; }
        public Nullable<decimal> Updated_Balance { get; set; }
        public Nullable<bool> IsPatronTransfer { get; set; }
        public Nullable<bool> IsCardDeposite { get; set; }
    }
}
