//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsNotification
    {
        public int PatronsNotificationID { get; set; }
        public Nullable<int> PatronID { get; set; }
        public string NotificationContent { get; set; }
        public Nullable<System.DateTime> DateTimeSent { get; set; }
        public string NotificationType { get; set; }
    }
}
