//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatronsOrder()
        {
            this.PatronsOrdersDetails = new HashSet<PatronsOrdersDetail>();
        }
    
        public int PatronsOrdersID { get; set; }
        public int HotelID { get; set; }
        public int PatronID { get; set; }
        public Nullable<System.DateTime> DateTimeOfOrder { get; set; }
        public bool BarAcceptedOrder { get; set; }
        public bool BarStartedOrder { get; set; }
        public bool BarCompletedOrder { get; set; }
        public Nullable<bool> OrderCollected { get; set; }
        public Nullable<System.DateTime> DateTimeCollected { get; set; }
        public string SpecialCode { get; set; }
        public string ScanOfCodeCollected { get; set; }
        public Nullable<decimal> FinalAmountForOrder { get; set; }
        public bool Paid { get; set; }
        public string PaymentGatewayReturnID { get; set; }
        public string PatronsOrderNotes { get; set; }
        public Nullable<int> BarStaffWhoStartedOrder { get; set; }
        public Nullable<int> BarStaffWhoCompletedOrder { get; set; }
        public Nullable<int> BarStaffWhoDeliveredOrder { get; set; }
        public Nullable<int> LinQ { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Patron Patron { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronsOrdersDetail> PatronsOrdersDetails { get; set; }
    }
}
