//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsFavourite
    {
        public int PatronsFavouriteID { get; set; }
        public int HotelID { get; set; }
        public int PatronID { get; set; }
        public int HotelCatagoryID { get; set; }
        public int HotelSubCatagoryID { get; set; }
        public int HotelMenuID { get; set; }
    }
}
