//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsSessionToken
    {
        public int PatronsSessionTokenID { get; set; }
        public int PatronID { get; set; }
        public System.Guid SessionToken { get; set; }
        public System.DateTime DateTimeGiven { get; set; }
        public Nullable<System.DateTime> DateTimeExpiry { get; set; }
        public bool fbLogin { get; set; }
    
        public virtual Patron Patron { get; set; }
    }
}
