//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsGroupInvitation
    {
        public int PatronsGroupInvitationID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> MasterPatronID { get; set; }
        public int PatronsGroupID { get; set; }
        public int PatronID { get; set; }
        public Nullable<System.DateTime> RequestSentDateTime { get; set; }
        public Nullable<System.DateTime> RequestAccepedDateTime { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
    }
}
