//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsPaymentMethod
    {
        public int PatronsPaymentMethodID { get; set; }
        public int PatronID { get; set; }
        public string PaymentType { get; set; }
        public string PaymentCardholderName { get; set; }
        public string PaymentCardType { get; set; }
        public string PaymentCardNumberEncrypted { get; set; }
        public string PaymentCardCvvCodeEncrypted { get; set; }
        public string PaymentCardExpiryEncrypted { get; set; }
    
        public virtual Patron Patron { get; set; }
    }
}
