//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronsHotelLogIn
    {
        public int PatronsHotelLogInsID { get; set; }
        public int PatronID { get; set; }
        public int HotelID { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public Nullable<System.DateTime> LogoutDateTime { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
