//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronWithdrawalTransection
    {
        public int PatronWithdrawalTransectionID { get; set; }
        public Nullable<int> PatronID { get; set; }
        public Nullable<decimal> Withdrawal_Amount { get; set; }
        public Nullable<System.DateTime> WithdrawalDatetime { get; set; }
        public Nullable<decimal> Previouse_Balance { get; set; }
        public Nullable<decimal> Updated_Balance { get; set; }
    }
}
