//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronPurchaseTransection
    {
        public int PatronPurchaseTransectionID { get; set; }
        public Nullable<int> PatronID { get; set; }
        public Nullable<int> PatronsOrdersID { get; set; }
        public Nullable<System.DateTime> PurchaseDatetime { get; set; }
        public Nullable<decimal> AmountPaidInOrder { get; set; }
    }
}
