//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatesG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatesG()
        {
            this.HotelEmployees = new HashSet<HotelEmployee>();
            this.Hotels = new HashSet<Hotel>();
        }
    
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateNameAbbreviation { get; set; }
        public Nullable<decimal> StateCentreLat { get; set; }
        public Nullable<decimal> StateCentreLong { get; set; }
        public Nullable<decimal> StateCityLat { get; set; }
        public Nullable<decimal> StateCityLong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelEmployee> HotelEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}
