//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackGroupOrder
    {
        public int TrackGroupOrderID { get; set; }
        public int HotelID { get; set; }
        public Nullable<int> PatronID { get; set; }
        public Nullable<int> PatronsGroupID { get; set; }
        public Nullable<decimal> FinalAmountForOrder { get; set; }
        public string PaymentGatewayReturnID { get; set; }
        public Nullable<System.DateTime> DateTimeOfOrder { get; set; }
        public string PatronsOrderNotes { get; set; }
        public Nullable<int> OpenMinutes { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
