//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkingBuddy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackGroupOrderDetail
    {
        public int TrackGroupOrderDetailID { get; set; }
        public int HotelMenuItemID { get; set; }
        public Nullable<int> QTYOrdered { get; set; }
        public Nullable<int> HotelSpecialID { get; set; }
        public Nullable<decimal> AcceptedPricePerItem { get; set; }
        public string PatronsOrderDetailsNotes { get; set; }
        public Nullable<int> TrackGroupOrderID { get; set; }
    }
}
